
pub const PAUSE_OR_SHUTDOWN: &str = "PAUSE_OR_SHUTDOWN";
pub const BOT_IS_ACTIVE: &str = "BOT_IS_ACTIVE";
pub const INVALID_FIRST_OR_LAST_AMOUNT: &str = "INVALID_FIRST_OR_LAST_AMOUNT";
pub const ORACLE_PRICE_EXCEPTION: &str = "ORACLE_PRICE_EXCEPTION";
pub const INVALID_PAIR_ID: &str = "INVALID_PAIR_ID";
pub const LESS_BASE_TOKEN: &str = "LESS_BASE_TOKEN";
pub const LESS_QUOTE_TOKEN: &str = "LESS_QUOTE_TOKEN";
pub const BOT_NOT_EXIST: &str = "BOT_NOT_EXIST";
pub const NO_PERMISSION: &str = "NO_PERMISSION";
pub const INVALID_PRICE_OR_NO_PERMISSION: &str = "INVALID_PRICE_OR_NO_PERMISSION";
pub const INVALID_MAKER_ORDERS: &str = "INVALID_MAKER_ORDERS";
pub const LESS_TOKEN_SELL: &str = "LESS_TOKEN_SELL";
pub const INVALID_TOKEN: &str = "INVALID_TOKEN";
pub const LESS_DEPOSIT_AMOUNT: &str = "LESS_DEPOSIT_AMOUNT";
pub const INVALID_USER: &str = "INVALID_USER";
pub const INVALID_NEXT_BOT_ID: &str = "INVALID_NEXT_BOT_ID";
pub const INVALID_BOT_ID_FOR_BOT_MAP: &str = "INVALID_BOT_ID_FOR_BOT_MAP";
pub const INVALID_BOT_ID_FOR_ORDER_MAP: &str = "INVALID_BOT_ID_FOR_ORDER_MAP";
pub const INVALID_ORDER_POSITION_LEN: &str = "INVALID_ORDER_POSITION_LEN";
pub const INVALID_ORDER_TOKEN: &str = "INVALID_ORDER_TOKEN";
pub const INVALID_ORDER_AMOUNT: &str = "INVALID_ORDER_AMOUNT";
pub const INVALID_ORDER_MATCHING: &str = "INVALID_ORDER_MATCHING";
pub const INVALID_PRICE: &str = "INVALID_PRICE";
pub const INVALID_REVENUE: &str = "INVALID_REVENUE";
pub const INVALID_BOT_ID: &str = "INVALID_BOT_ID";
pub const BOT_CLOSED: &str = "BOT_CLOSED";
pub const BOT_DISABLE: &str = "BOT_DISABLE";
pub const INVALID_PARAM: &str = "INVALID_PARAM";
pub const ERR_NOT_ALLOWED: &str = "ERR_NOT_ALLOWED";
pub const INVALID_TRANSFER_DATA: &str = "INVALID_TRANSFER_DATA";
pub const INVALID_BALANCE: &str = "INVALID_BALANCE";
pub const PAIR_EXIST: &str = "PAIR_EXIST";
pub const BOT_EXPIRED: &str = "BOT_EXPIRED";
pub const INVALID_PROTOCOL_FEE: &str = "INVALID_PROTOCOL_FEE";
pub const INVALID_FORWARD_OR_REVERSE: &str = "INVALID_FORWARD_OR_REVERSE";
pub const INVALID_AMOUNT: &str = "INVALID_AMOUNT";
pub const LESS_STORAGE_FEE: &str = "LESS_STORAGE_FEE";
pub const ALREADY_NEW: &str = "ALREADY_NEW";
pub const HAD_SHUTDOWN: &str = "HAD_SHUTDOWN";
pub const CAN_NOT_READ_STATE: &str = "CAN_NOT_READ_STATE";
pub const INVALID_TAKE_PARAM: &str = "INVALID_TAKE_PARAM";
pub const LESS_TOKEN_STORAGE_FEE: &str = "LESS_TOKEN_STORAGE_FEE";
pub const WITHDRAW_UNOWNED_ASSET_ERROR: &str = "WITHDRAW_UNOWNED_ASSET_ERROR";
pub const INVALID_ORACLE_ID: &str = "INVALID_ORACLE_ID";
pub const INVALID_PAIR_PRICE_LENGTH: &str = "INVALID_PAIR_PRICE_LENGTH";
pub const INVALID_BASE_AMOUNT: &str = "INVALID_BASE_AMOUNT";
pub const INVALID_QUOTE_AMOUNT: &str = "INVALID_QUOTE_AMOUNT";
pub const CAN_NOT_TRIGGER: &str = "CAN_NOT_TRIGGER";











