
pub const PAUSE_OR_SHUTDOWN: &str = "PAUSE_OR_SHUTDOWN";
pub const INVALID_FIRST_OR_LAST_AMOUNT: &str = "INVALID_FIRST_OR_LAST_AMOUNT";
pub const ORACLE_PRICE_EXCEPTION: &str = "ORACLE_PRICE_EXCEPTION";
pub const INVALID_PAIR_ID: &str = "INVALID_PAIR_ID";
pub const LESS_BASE_TOKEN: &str = "LESS_BASE_TOKEN";
pub const LESS_QUOTE_TOKEN: &str = "LESS_QUOTE_TOKEN";
pub const BOT_NOT_EXIST: &str = "BOT_NOT_EXIST";
pub const NO_PERMISSION: &str = "NO_PERMISSION";
pub const INVALID_MAKER_ORDERS: &str = "INVALID_MAKER_ORDERS";
pub const LESS_TOKEN_SELL: &str = "LESS_TOKEN_SELL";
pub const INVALID_TOKEN: &str = "INVALID_TOKEN";
pub const INVALID_NEXT_BOT_ID: &str = "INVALID_NEXT_BOT_ID";
pub const INVALID_BOT_ID_FOR_BOT_MAP: &str = "INVALID_BOT_ID_FOR_BOT_MAP";
pub const INVALID_BOT_ID_FOR_ORDER_MAP: &str = "INVALID_BOT_ID_FOR_ORDER_MAP";
pub const INVALID_ORDER_POSITION_LEN: &str = "INVALID_ORDER_POSITION_LEN";
pub const INVALID_ORDER_TOKEN: &str = "INVALID_ORDER_TOKEN";
pub const INVALID_ORDER_AMOUNT: &str = "INVALID_ORDER_AMOUNT";
pub const INVALID_PRICE: &str = "INVALID_PRICE";
pub const INVALID_REVENUE: &str = "INVALID_REVENUE";
pub const INVALID_BOT_ID: &str = "INVALID_BOT_ID";
pub const BOT_CLOSED: &str = "BOT_CLOSED";
pub const BOT_DISABLE: &str = "BOT_DISABLE";
pub const INVALID_PARAM: &str = "INVALID_PARAM";
pub const ERR_NOT_ALLOWED: &str = "ERR_NOT_ALLOWED";
pub const INVALID_TRANSFER_DATA: &str = "INVALID_TRANSFER_DATA";
pub const INVALID_BALANCE: &str = "INVALID_BALANCE";
pub const PAIR_EXIST: &str = "PAIR_EXIST";
pub const BOT_EXPIRED: &str = "BOT_EXPIRED";


